//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Materno
    {
        public int ID { get; set; }
        public string Mes_Año { get; set; }
        public int Numero_Semana { get; set; }
        public string Nivel { get; set; }
        public string Nombre_Estudiante { get; set; }
        public Nullable<int> Lunes { get; set; }
        public Nullable<int> Martes { get; set; }
        public Nullable<int> Miercoles { get; set; }
        public Nullable<int> Jueves { get; set; }
        public Nullable<int> Viernes { get; set; }
    
        public virtual Estado_Asistencia Estado_Asistencia { get; set; }
        public virtual Estado_Asistencia Estado_Asistencia1 { get; set; }
        public virtual Estado_Asistencia Estado_Asistencia2 { get; set; }
        public virtual Estado_Asistencia Estado_Asistencia3 { get; set; }
        public virtual Estado_Asistencia Estado_Asistencia4 { get; set; }
    }
}
