//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activos_Electricos
    {
        public int Id_Electrico { get; set; }
        public string Codigo_Activo_Electrico { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public string Serie { get; set; }
        public string Fecha_Compra { get; set; }
        public string Fecha_Salida { get; set; }
        public Nullable<int> Vida_Util_Meses { get; set; }
        public Nullable<double> Costo_Adquisitivo { get; set; }
        public Nullable<double> Deprec_Mes { get; set; }
        public Nullable<double> Deprec_Acum { get; set; }
        public Nullable<double> Valor_Libros { get; set; }
    }
}
