//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Activos_Computacion
    {
        public int Id_Computacion { get; set; }
        [Display(Name="Código")]
        public string Codigo_Activo_Computo { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public string Serie { get; set; }
        [Display(Name = "Fecha Compra")]
        public string Fecha_Copmra { get; set; }
        [Display(Name = "Fecha Salida")]
        public string Fecha_Salida { get; set; }

        [Display(Name = "Vida Útil (Mes)")]
        public Nullable<int> Vida_Util_Meses { get; set; }
        [Display(Name = "Costo Adquisitivo")]
        public Nullable<double> Costo_Adquisitivo { get; set; }
        [Display(Name = "Deprec. Mes")]
        public Nullable<double> Deprec_Mes { get; set; }
        [Display(Name = "Deprec. Acum")]
        public Nullable<double> Deprec_Acum { get; set; }
        [Display(Name = "Valor Libros")]
        public Nullable<double> Valor_Libros { get; set; }
    }
}
