
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Activos_Recreativos
    {
        public int Id_Activo_Recreativo { get; set; }
        public string Codigo_Activo_Recreativo { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public string Serie { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime Fecha_Compra { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime Fecha_Salida { get; set; }

        public int Vida_Util_Meses
        {
            get
            {
                return Math.Abs((Fecha_Compra.Month - Fecha_Salida.Month) + 12 * (Fecha_Salida.Year - Fecha_Compra.Year));
            }
        }
        public Nullable<double> Costo_Adquisitivo { get; set; }
        public Nullable<double> Valor_Libros { get; set; }
    }
}
