//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public int Id_Estudiante { get; set; }
        public string Nombre_Completo { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Responsable { get; set; }
        public string Id_Nivel { get; set; }
        public Nullable<int> Asistencia { get; set; }
        public string Ausencia { get; set; }
        public Nullable<int> Telefono { get; set; }
    
        public virtual Niveles Niveles { get; set; }
    }
}
