//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Estudiantes_List
    {
        public int ID { get; set; }
        public string Nombre_Estudiante { get; set; }
        public string Cedula { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime fechaNacimiento { get; set; }
        public int Age
        {
            get
            {
                DateTime now = DateTime.Today;
                int age = now.Year - fechaNacimiento.Year;
                if (fechaNacimiento > now.AddYears(-age)) age--;
                return age;
            }
        }
        public Nullable<int> Numero_Contacto { get; set; }
        public Nullable<int> Nivel { get; set; }

        public virtual Nivel_Estudiante Nivel_Estudiante { get; set; }
    }
}
