//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public int IDESTUDIANTE { get; set; }
        public string NOMBRECOMPLETO { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string RESPONSABLE { get; set; }
        public string ID_NIVEL { get; set; }
        public Nullable<int> ASISTENCIA { get; set; }
        public string AUSENCIA { get; set; }
        public Nullable<int> TELEFONO { get; set; }
    
        public virtual Niveles Niveles { get; set; }
    }
}
