//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int ID_FUNCIONARIO { get; set; }
        public string NOMBRECOMPLETO { get; set; }
        public Nullable<int> NUM_TEL { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public string ID_CARGO { get; set; }
    
        public virtual Cargos Cargos { get; set; }
    }
}
