//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int Id_Funcionario { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<int> Num_Tel { get; set; }
        public string Correo_Electronico { get; set; }
        public string Id_Cargo { get; set; }
    
        public virtual Cargos Cargos { get; set; }
    }
}
