//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_COCINA
    {
        public string CODIGO_COCINA { get; set; }
        public string PRODUCTO { get; set; }
        public string MEDIDA { get; set; }
        public string EXISTENCIA_INICIAL { get; set; }
        public int ENTRADAS { get; set; }
        public int SALIDAS { get; set; }
        public int EXISTENCIAS { get; set; }
    }
}
