//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AADFLDEntities : DbContext
    {
        public AADFLDEntities()
            : base("name=AADFLDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activos_Computacion> Activos_Computacion { get; set; }
        public virtual DbSet<Activos_Electricos> Activos_Electricos { get; set; }
        public virtual DbSet<Activos_Recreativos> Activos_Recreativos { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Inventario_Cocina> Inventario_Cocina { get; set; }
        public virtual DbSet<Niveles> Niveles { get; set; }
        public virtual DbSet<Reserva_Matriculas> Reserva_Matriculas { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Servicio_Comunales> Servicio_Comunales { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
