//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreKinder
    {
        public int ID { get; set; }
        public string AnoMes { get; set; }
        public string Nombre_Estudiante { get; set; }
        public int Nivel { get; set; }
        public Nullable<int> NumeroSemana { get; set; }
        public int Lunes { get; set; }
        public int Martes { get; set; }
        public int Miercoles { get; set; }
        public int Jueves { get; set; }
        public int Viernes { get; set; }
    
        public virtual Estado_Asistencia Estado_Asistencia { get; set; }
        public virtual Estado_Asistencia Estado_Asistencia1 { get; set; }
        public virtual Estado_Asistencia Estado_Asistencia2 { get; set; }
        public virtual Estado_Asistencia Estado_Asistencia3 { get; set; }
        public virtual Estado_Asistencia Estado_Asistencia4 { get; set; }
        public virtual Nivel_Estudiante Nivel_Estudiante { get; set; }
    }
}
