//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva_Matriculas
    {
        public int ID_RESERVA { get; set; }
        public string NOMBRETUTOR { get; set; }
        public string CEDULATUTOR { get; set; }
        public string CORREOTUTOR { get; set; }
        public int NUM_TEL { get; set; }
        public string NOMBREALUMNO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string SEXO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string PROVINCIA { get; set; }
        public string DIRECCIONDETALLADA { get; set; }
        public System.DateTime FECHA_CITA { get; set; }
        public string HORA_CITA { get; set; }
    }
}
