//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva_Matriculas
    {
        public int Id_Reserva { get; set; }
        public string Nombre_Tutor { get; set; }
        public string Cedula_Tutor { get; set; }
        public string Correo_Tutor { get; set; }
        public int Num_Tel { get; set; }
        public string Nombre_Alumno { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Sexo { get; set; }
        public string Nacinalidad { get; set; }
        public string Provincia { get; set; }
        public string Direccion_Detallada { get; set; }
        public System.DateTime Fecha_Cita { get; set; }
        public string Hora_Cita { get; set; }
    }
}
