//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio_Comunales
    {
        public int Id_Servicio_Comunal { get; set; }
        public string Nombre_Servicio { get; set; }
        public string Nombre_Persona { get; set; }
        public string Email { get; set; }
        public Nullable<int> Num_Tel { get; set; }
        public string Mensaje { get; set; }
    }
}
