//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio_Comunales
    {
        public int ID_SERVICIO_COMUNAL { get; set; }
        public string NOMBRE_SERVICIO { get; set; }
        public string NOMBRE_PERSONA { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> NUMTEL { get; set; }
        public string MENSAJE { get; set; }
    }
}
