//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testautenticacion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        [Range(1, 999999999, ErrorMessage = "La cédula consta de 9 digitos")]
        public int idUsuario { get; set; }
        public string Nombres { get; set; }
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Correo { get; set; }

        [StringLength(18, ErrorMessage = "La clave debe contar con una Mayuscula, número y caracter especial. 8 dígitos máximo", MinimumLength = 8)]
        [RegularExpression(@"^((?=.*[a-z])(?=.*[A-Z])(?=.*\d)).+$")]
        [DataType(DataType.Password)]
        [Display(Name = "Clave")]

        public string Clave { get; set; }
        public string Estado { get; set; }
        public int IdRol { get; set; }

        public virtual Rol Rol { get; set; }
    }
}

